### ISSUE TITLE
Day24 Challenge

### ISSUE THREAD

**Issue by CharlyKeleb** [satoshi0212/visionOS_30Days#24]
When I play the video, it plays for the first time, but when I close the immersive space and open the video again, I only hear the sounds and dont see the visuals

**Comment by satoshi0212** [comment]
I fixed avplayer lifecycle in a way that leaves it to the view instead of the viewModel.
https://github.com/satoshi0212/visionOS_30Days/commit/3e718407d1a3a880b37338b1feb5d2d93b9586dd

**Comment by CharlyKeleb** [comment]
Thanks
